version: '3.0'

services:
  
  rasa:
    build: .
    image: rasa-asistentes:2.4.3rc2
    ports:
      - 5005:5005
    volumes:
      - ./models:/app/models
      - ./config:/app/config
    command:
      - rasa
      - run
      - --enable-api
      - --model
      - /app/models
      - --endpoints
      - /app/config/endpoints.yml

  action-server:
    build: actions
    image: rasa-asistentes-actions:2.4.1
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
    command:
      - python
      - -m
      - rasa_sdk
      - --actions
      - actions